FROM python:3.8.13

COPY ./requirements.txt /src/requirements.txt

WORKDIR /src

RUN pip install --upgrade pip && pip install -r requirements.txt
RUN apt-get update && apt-get install -y libpq-dev
RUN pip install --upgrade psycopg2-binary

COPY ./ /src/

CMD python /src/populate_db.py